/*
 * ClubFrame.java
 *
 * Created on 2013
 */

package MyFrame;

import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.JOptionPane;

import MyDao.Until;

/**
 * 
 * @author fengche
 */
public class ClubSerchFrame extends javax.swing.JInternalFrame {

	/** Creates new form ClubFrame */
	public ClubSerchFrame() {
		initComponents();
		this.setLocation(300, 100);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField_name = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextField_number = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField_place = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField_time = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField_mainmanger = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField_other1 = new javax.swing.JTextField();
		jTextField_other2 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jTextField_teacher = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea_jianjie = new javax.swing.JTextArea();
		jTextField_xingzhi = new javax.swing.JTextField();
		jButton_ok = new javax.swing.JButton();
		jTextField_xibie = new javax.swing.JTextField();
		jButton_del = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u67e5\u627e");

		jLabel1.setText("\u540d\u79f0\uff1a");

		jLabel2.setText("\u6027\u8d28\uff1a");

		jLabel3.setText("\u4eba\u6570\uff1a");

		jTextField_number.setEditable(false);

		jLabel4.setText("\u6d3b\u52a8\u5730\u70b9\uff1a");

		jTextField_place.setEditable(false);

		jLabel5.setText("\u6d3b\u52a8\u65f6\u95f4\uff1a");

		jTextField_time.setEditable(false);

		jLabel6.setText("\u4e3b\u8981\u8d1f\u8d23\u4eba\uff1a");

		jTextField_mainmanger.setEditable(false);

		jLabel7.setText("\u5176\u4ed6\u8d1f\u8d23\u4eba\uff1a");

		jTextField_other1.setEditable(false);
		jTextField_other1.setText("\u65e0");

		jTextField_other2.setEditable(false);
		jTextField_other2.setText("\u65e0");

		jLabel8.setText("\u6240\u5c5e\u7cfb\u522b\uff1a");

		jLabel9.setText("\u6307\u5bfc\u8001\u5e08\uff1a");

		jTextField_teacher.setEditable(false);
		jTextField_teacher.setText("\u65e0");

		jLabel10.setText("\u793e\u56e2\u7b80\u4ecb\uff1a");

		jTextArea_jianjie.setColumns(20);
		jTextArea_jianjie.setEditable(false);
		jTextArea_jianjie.setRows(5);
		jScrollPane1.setViewportView(jTextArea_jianjie);

		jTextField_xingzhi.setEditable(false);

		jButton_ok.setText("\u786e\u5b9a");
		jButton_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_okActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

		jTextField_xibie.setEditable(false);

		jButton_del.setText("\u5220\u9664");
		jButton_del.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_delActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(53, 53, 53)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField_mainmanger,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				81,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel7)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField_other1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				64,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField_other2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				71,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jLabel9)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField_teacher,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				88,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField_name,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				144,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				52,
																				52,
																				52)
																		.addComponent(
																				jButton_ok)
																		.addGap(
																				72,
																				72,
																				72))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel10)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jScrollPane1,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												488,
																												Short.MAX_VALUE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel2)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField_xingzhi,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												134,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												29,
																												29,
																												29)
																										.addComponent(
																												jLabel8)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jTextField_xibie,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												148,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												34,
																												Short.MAX_VALUE)
																										.addComponent(
																												jLabel3)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jTextField_number,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												47,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel4)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField_place,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												195,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												47,
																												47,
																												47)
																										.addComponent(
																												jLabel5)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jTextField_time,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												174,
																												Short.MAX_VALUE))
																						.addComponent(
																								jButton_del))
																		.addGap(
																				80,
																				80,
																				80)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(26, 26, 26)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField_name,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton_ok))
														.addComponent(jLabel1))
										.addGap(34, 34, 34)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField_number,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																jTextField_xingzhi,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel8)
														.addComponent(
																jTextField_xibie,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(jLabel4)
														.addComponent(
																jTextField_place,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField_time,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField_mainmanger,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(
																jTextField_other1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField_other2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9)
														.addComponent(
																jTextField_teacher,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(34, 34, 34)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel10)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																172,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18).addComponent(
												jButton_del).addContainerGap(
												32, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	/**
	 *数据库删除club按钮
	 */
	private void jButton_delActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		Until until = new Until();//声明一个until对象
		until.deleteClub(this.jTextField_name.getText());//调用删除方法
		resetall();//重置
	}
	/**
	 *确认事件按钮
	 */
	private void jButton_okActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		ArrayList<String> arrayList = new ArrayList<String>();//声明一个arraylist对象
		if (!this.jTextField_name.getText().equals("")) {
			arrayList = searchclub(this.jTextField_name.getText());
			this.jTextField_name.setText(arrayList.get(0));
			this.jTextField_xingzhi.setText(arrayList.get(1));
			this.jTextField_xibie.setText(arrayList.get(2));
			this.jTextField_number.setText(arrayList.get(3));
			this.jTextField_place.setText(arrayList.get(4));
			this.jTextField_time.setText(arrayList.get(5));
			this.jTextField_mainmanger.setText(arrayList.get(6));
			this.jTextField_other1.setText(arrayList.get(7));
			this.jTextField_other2.setText(arrayList.get(8));
			this.jTextField_teacher.setText(arrayList.get(9));
			this.jTextArea_jianjie.setText(arrayList.get(10));
		} else {
			JOptionPane.showMessageDialog(null, "名称不能为空!");//信息提示框
		}
	}
	/**
	 *club查询方法
	 */
	private ArrayList<String> searchclub(String Cname) {
		ArrayList<String> arrayList = new ArrayList<String>();
		ArrayList<String> aList = new ArrayList<String>();
		Until until;//声明一个until对象
		try {
			until = new Until();
			arrayList = until.selectall("Club");
		} catch (Exception e) {
			e.printStackTrace();
		}
		Iterator<String> iterator = arrayList.iterator();//声明一个迭代器对象
		while (iterator.hasNext()) {
			String string = iterator.next();
			if (string.equals(jTextField_name.getText())) {
				aList.add(string);
				aList.add(iterator.next());
				aList.add(iterator.next());
				aList.add(iterator.next());
				aList.add(iterator.next());
				aList.add(iterator.next());
				aList.add(iterator.next());
				aList.add(iterator.next());
				aList.add(iterator.next());
				aList.add(iterator.next());
				aList.add(iterator.next());
			}
		}
		return aList;
	}
	/**
	 *重置的方法
	 */
	private void resetall(){
		this.jTextField_name.setText("");
		this.jTextField_xingzhi.setText("");
		this.jTextField_xibie.setText("");
		this.jTextField_number.setText("");
		this.jTextField_place.setText("");
		this.jTextField_time.setText("");
		this.jTextField_mainmanger.setText("");
		this.jTextField_other1.setText("");
		this.jTextField_other2.setText("");
		this.jTextField_teacher.setText("");
		this.jTextArea_jianjie.setText("");
	}
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton_del;
	private javax.swing.JButton jButton_ok;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea_jianjie;
	private javax.swing.JTextField jTextField_mainmanger;
	private javax.swing.JTextField jTextField_name;
	private javax.swing.JTextField jTextField_number;
	private javax.swing.JTextField jTextField_other1;
	private javax.swing.JTextField jTextField_other2;
	private javax.swing.JTextField jTextField_place;
	private javax.swing.JTextField jTextField_teacher;
	private javax.swing.JTextField jTextField_time;
	private javax.swing.JTextField jTextField_xibie;
	private javax.swing.JTextField jTextField_xingzhi;
	// End of variables declaration//GEN-END:variables

}