/*
 * ClubPeopleShoeFrame.java
 *
 * Created on 2013
 */

package MyFrame;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import MyDao.Until;

/**
 *协会人员展示的类
 * @author fengche
 */
public class ClubPeopleShoeFrame extends javax.swing.JInternalFrame {

	/** Creates new form ClubPeopleShoeFrame */
	public ClubPeopleShoeFrame() {
		initComponents();
		this.setLocation(300, 100);//设置窗口位置
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		jLabel2 = new javax.swing.JLabel();
		jComboBox_club = new javax.swing.JComboBox();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable = new javax.swing.JTable();
		jButton_ok = new javax.swing.JButton();
		setClosable(true);
		setIconifiable(true);
		setTitle("\u793e\u56e2\u6210\u5458");
		jLabel2.setText("\u6240\u5c5e\u793e\u56e2\uff1a");
		jComboBox_club.setModel(new javax.swing.DefaultComboBoxModel(
				ClubLoad()));
		jTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
		}, new String[] { "编号", "姓名", "学号", "年龄", "班级", "爱好" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false };
			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTable);
		jButton_ok.setText("\u786e\u5b9a");
		jButton_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_okActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(40, 40, 40)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																748,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jComboBox_club,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				187,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				55,
																				55,
																				55)
																		.addComponent(
																				jButton_ok)))
										.addContainerGap(38, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(26, 26, 26).addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(
										jComboBox_club,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton_ok)).addGap(27, 27, 27)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 366,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(63, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	/**
	 *确定事件按钮
	 */
	private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {
		String clubname = this.jComboBox_club.getSelectedItem().toString();
		ArrayList<String> arrayList = new ArrayList<String>();
		try {
			Until until = new Until();//声明一个until对象
			arrayList = until.selectClubpeople(clubname);//获取people对象
			DefaultTableModel model = (DefaultTableModel) this.jTable
					.getModel();//获取一个modil
			// 清空table
			for (int index = model.getRowCount() - 1; index >= 0; index--) {
				model.removeRow(index);
			}
			int i = 1;
			Iterator<String> iterator = arrayList.iterator();//声明一个迭代器对象
			String it = iterator.next();//调用迭代器对象
			//table填充
			while (it != "") {
				Vector<String> vector = new Vector<String>();
				try {
					vector.add(i + "");
					vector.add(iterator.next());
					vector.add(iterator.next());
					vector.add(iterator.next());
					vector.add(iterator.next());
					vector.add(iterator.next());
				} catch (Exception e) {
				}
				i++;
				model.addRow(vector);
				it = iterator.next();
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "查询完毕");//信息提示框
		}
	}
	/**
	 *获取所有club对象的方法
	 */
	private String[] ClubLoad() {
		ArrayList<String> arrayList = new ArrayList<String>();//声明一个arraylist对象
		String[] sc = null;
		try {
			Until until = new Until();//声明一个until对象
			arrayList = until.selectClubName("ST_name", "Club");
			String[] strings = new String[arrayList.size()];
			strings = arrayList.toArray(strings);
			sc = strings;
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "数据库查询错误");//信息提示框
		}
		return sc;
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton_ok;
	private javax.swing.JComboBox jComboBox_club;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable;
	// End of variables declaration//GEN-END:variables

}