/*
 * ClubFrame.java
 * @author fengche
 * Created on2013
 *添加协会的类
 */

package MyFrame;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import MyDao.Until;

/**
 *添加club的窗口
 * @author  fengche
 */
public class ClubAddFrame extends javax.swing.JInternalFrame {

	/** Creates new form ClubFrame */
	public ClubAddFrame() {
		initComponents();
		this.setLocation(300, 100);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField_name = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jComboBox_quale = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		jTextField_number = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField_place = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField_time = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField_mainmanger = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField_other1 = new javax.swing.JTextField();
		jTextField_other2 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jComboBox_xibie = new javax.swing.JComboBox();
		jLabel9 = new javax.swing.JLabel();
		jTextField_teacher = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea_jianjie = new javax.swing.JTextArea();
		jButton_ok = new javax.swing.JButton();
		jButton_esc = new javax.swing.JButton();
		jButton_reset = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u793e\u56e2\u6dfb\u52a0");

		jLabel1.setText("\u540d\u79f0\uff1a");

		jLabel2.setText("\u6027\u8d28\uff1a");

		jComboBox_quale.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "科技型组织", "学习型组织", "运动型组织" }));

		jLabel3.setText("\u4eba\u6570\uff1a");

		jLabel4.setText("\u6d3b\u52a8\u5730\u70b9\uff1a");

		jLabel5.setText("\u6d3b\u52a8\u65f6\u95f4\uff1a");

		jLabel6.setText("\u4e3b\u8981\u8d1f\u8d23\u4eba\uff1a");

		jLabel7.setText("\u5176\u4ed6\u8d1f\u8d23\u4eba\uff1a");

		jTextField_other1.setText("\u65e0");

		jTextField_other2.setText("\u65e0");

		jLabel8.setText("\u6240\u5c5e\u7cfb\u522b\uff1a");

		jComboBox_xibie.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "信息学院", "会计学院" }));

		jLabel9.setText("\u6307\u5bfc\u8001\u5e08\uff1a");

		jTextField_teacher.setText("\u65e0");

		jLabel10.setText("\u793e\u56e2\u7b80\u4ecb\uff1a");

		jTextArea_jianjie.setColumns(20);
		jTextArea_jianjie.setRows(5);
		jScrollPane1.setViewportView(jTextArea_jianjie);

		jButton_ok.setText("\u786e\u5b9a");
		jButton_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_okActionPerformed(evt);
			}
		});

		jButton_esc.setText("\u53d6\u6d88");
		jButton_esc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_escActionPerformed(evt);
			}
		});

		jButton_reset.setText("\u91cd\u7f6e");
		jButton_reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_resetActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(46, 46, 46)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel1)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jTextField_name,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				144,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(
																																				18,
																																				18,
																																				18)
																																		.addComponent(
																																				jLabel2)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jComboBox_quale,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel6)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jTextField_mainmanger,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				81,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(
																																				18,
																																				18,
																																				18)
																																		.addComponent(
																																				jLabel7)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jTextField_other1,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				64,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				jTextField_other2,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				71,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												18,
																												Short.MAX_VALUE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel3)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField_number,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												47,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												118,
																												Short.MAX_VALUE)
																										.addComponent(
																												jLabel4)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField_place,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												77,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												70,
																												70,
																												70)))
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel8)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jComboBox_xibie,
																												0,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jLabel9)
																														.addComponent(
																																jLabel5))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																jTextField_teacher)
																														.addComponent(
																																jTextField_time,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																78,
																																Short.MAX_VALUE)))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel10)
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton_ok)
																										.addGap(
																												27,
																												27,
																												27)
																										.addComponent(
																												jButton_reset)
																										.addGap(
																												28,
																												28,
																												28)
																										.addComponent(
																												jButton_esc))
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								483,
																								Short.MAX_VALUE))))
										.addGap(48, 48, 48)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(26, 26, 26)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField_name,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel2)
																		.addComponent(
																				jComboBox_quale,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel8)
																		.addComponent(
																				jComboBox_xibie,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(jLabel1))
										.addGap(20, 20, 20)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jLabel5)
														.addComponent(
																jTextField_time,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField_place,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField_number,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField_mainmanger,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9)
														.addComponent(jLabel7)
														.addComponent(
																jTextField_other1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField_other2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField_teacher,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(27, 27, 27)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel10)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																172,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												31, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton_ok)
														.addComponent(
																jButton_reset)
														.addComponent(
																jButton_esc))
										.addGap(24, 24, 24)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 *确定事件按钮
	 */
	private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			if (!this.jTextField_name.getText().equals("")) {
				clubinsert();//club插入数据库操作
				JOptionPane.showMessageDialog(null, "添加成功!");//信息提示框
				resetJt();//重置
			}
			else {
				JOptionPane.showMessageDialog(null, "名称不能为空！");//信息提示框
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "添加失败!");//信息提示框
		}
	}
	/**
	 *取消事件按钮
	 */
	private void jButton_escActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();//销毁当前窗口
	}
	/**
	 *重置事件按钮
	 */
	private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {
		resetJt();//重置事件
	}
	/**
	 *club插入数据库操作
	 */
	private void clubinsert() throws Exception{
		Until until = new Until();//声明一个until对象
		String name = this.jTextField_name.getText();
		String character = this.jComboBox_quale.getSelectedItem().toString();
		String xibie = this.jComboBox_xibie.getSelectedItem().toString();
		String number = this.jTextField_number.getText();
		String place = this.jTextField_place.getText();
		String time = jTextField_time.getText();
		String mainpeople = jTextField_mainmanger.getText();
		String others1 = jTextField_other1.getText();
		String others2 = jTextField_other2.getText();
		String teacher = jTextField_teacher.getText();
		String jianjie = jTextArea_jianjie.getText();
		until.insertClub(name, character, xibie, number, place, time, mainpeople, others1, others2, teacher, jianjie);//数据库插入方法
 	}
	/**
	 *重置方法
	 */
	private void resetJt(){
		this.jTextArea_jianjie.setText("");
		this.jTextField_mainmanger.setText("");
		this.jTextField_name.setText("");
		this.jTextField_number.setText("");
		this.jTextField_other1.setText("无");
		this.jTextField_other2.setText("无");
		this.jTextField_place.setText("");
		this.jTextField_teacher.setText(" 无");
		this.jTextField_time.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton_esc;
	private javax.swing.JButton jButton_ok;
	private javax.swing.JButton jButton_reset;
	private javax.swing.JComboBox jComboBox_quale;
	private javax.swing.JComboBox jComboBox_xibie;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea_jianjie;
	private javax.swing.JTextField jTextField_mainmanger;
	private javax.swing.JTextField jTextField_name;
	private javax.swing.JTextField jTextField_number;
	private javax.swing.JTextField jTextField_other1;
	private javax.swing.JTextField jTextField_other2;
	private javax.swing.JTextField jTextField_place;
	private javax.swing.JTextField jTextField_teacher;
	private javax.swing.JTextField jTextField_time;
	// End of variables declaration//GEN-END:variables

}