/*
 * MainFrame.java
 *
 * Created on 2013
 */

package MyFrame;

import java.awt.Image;
import java.beans.PropertyVetoException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author  fengche
 */
public class MainFrame extends javax.swing.JFrame {

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jDesktopPane1 = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu_ClubManage = new javax.swing.JMenu();
		jMenuItem_ClubAdd = new javax.swing.JMenuItem();
		jMenuItem_ClubSelect = new javax.swing.JMenuItem();
		jMenuItem_ShowPeople = new javax.swing.JMenuItem();
		jMenu_PeopleMenage = new javax.swing.JMenu();
		jMenuItem_PeopleAdd = new javax.swing.JMenuItem();
		jMenuItem_PeopleSelect = new javax.swing.JMenuItem();
		jMenu_Help = new javax.swing.JMenu();
		jMenuItem_About = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u793e\u56e2\u7ba1\u7406");
		setResizable(false);

		jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
		jDesktopPane1.setToolTipText("\u6211");

		jMenu_ClubManage.setText("\u793e\u56e2\u7ba1\u7406");

		jMenuItem_ClubAdd.setText("\u6dfb\u52a0");
		jMenuItem_ClubAdd
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jMenuItem_ClubAddActionPerformed(evt);
					}
				});
		jMenu_ClubManage.add(jMenuItem_ClubAdd);

		jMenuItem_ClubSelect.setText("\u67e5\u8be2");
		jMenuItem_ClubSelect
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jMenuItem_ClubSelectActionPerformed(evt);
					}
				});
		jMenu_ClubManage.add(jMenuItem_ClubSelect);

		jMenuItem_ShowPeople.setText("\u6210\u5458\u663e\u793a");
		jMenuItem_ShowPeople
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jMenuItem_ShowPeopleActionPerformed(evt);
					}
				});
		jMenu_ClubManage.add(jMenuItem_ShowPeople);

		jMenuBar1.add(jMenu_ClubManage);

		jMenu_PeopleMenage.setText("\u4eba\u5458\u7ba1\u7406");

		jMenuItem_PeopleAdd.setText("\u6dfb\u52a0");
		jMenuItem_PeopleAdd
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jMenuItem_PeopleAddActionPerformed(evt);
					}
				});
		jMenu_PeopleMenage.add(jMenuItem_PeopleAdd);

		jMenuItem_PeopleSelect.setText("\u67e5\u8be2");
		jMenuItem_PeopleSelect
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jMenuItem_PeopleSelectActionPerformed(evt);
					}
				});
		jMenu_PeopleMenage.add(jMenuItem_PeopleSelect);

		jMenuBar1.add(jMenu_PeopleMenage);

		jMenu_Help.setText("\u5e2e\u52a9");

		jMenuItem_About.setText("\u5173\u4e8e");
		jMenuItem_About.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem_AboutActionPerformed(evt);
			}
		});
		jMenu_Help.add(jMenuItem_About);

		jMenuBar1.add(jMenu_Help);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	/**
	 *关于菜单项事件
	 */
	private void jMenuItem_AboutActionPerformed(java.awt.event.ActionEvent evt) {
		HelpFrame help = new HelpFrame();
		help.setVisible(true);
		this.jDesktopPane1.add(help);
	}
	/**
	 *人员查询菜单项事件
	 */
	private void jMenuItem_PeopleSelectActionPerformed(
			java.awt.event.ActionEvent evt) {
		PeopleSerchFrame peopleSerchFrame = new PeopleSerchFrame();
		peopleSerchFrame.setVisible(true);
		this.jDesktopPane1.add(peopleSerchFrame);
	}
	/**
	 *人员添加菜单项事件
	 */
	private void jMenuItem_PeopleAddActionPerformed(
			java.awt.event.ActionEvent evt) {
		PeopleAddFrame peopleAddFrame = new PeopleAddFrame();
		peopleAddFrame.setVisible(true);
		this.jDesktopPane1.add(peopleAddFrame);
	}
	/**
	 *人员展示菜单项事件
	 */
	private void jMenuItem_ShowPeopleActionPerformed(
			java.awt.event.ActionEvent evt) {
		ClubPeopleShoeFrame clubPeopleShoeFrame = new ClubPeopleShoeFrame();
		clubPeopleShoeFrame.setVisible(true);
		this.jDesktopPane1.add(clubPeopleShoeFrame);
	}
	/**
	 *club查询菜单项事件
	 */
	private void jMenuItem_ClubSelectActionPerformed(
			java.awt.event.ActionEvent evt) {
		ClubSerchFrame clubSerchFrame = new ClubSerchFrame();
		clubSerchFrame.setVisible(true);
		this.jDesktopPane1.add(clubSerchFrame);
	}
	/**
	 *club添加菜单项事件
	 */
	private void jMenuItem_ClubAddActionPerformed(java.awt.event.ActionEvent evt) {
		ClubAddFrame clubFrame = new ClubAddFrame();
		clubFrame.setVisible(true);
		this.jDesktopPane1.add(clubFrame);
	}
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JDesktopPane jDesktopPane1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem_About;
	private javax.swing.JMenuItem jMenuItem_ClubAdd;
	private javax.swing.JMenuItem jMenuItem_ClubSelect;
	private javax.swing.JMenuItem jMenuItem_PeopleAdd;
	private javax.swing.JMenuItem jMenuItem_PeopleSelect;
	private javax.swing.JMenuItem jMenuItem_ShowPeople;
	private javax.swing.JMenu jMenu_ClubManage;
	private javax.swing.JMenu jMenu_Help;
	private javax.swing.JMenu jMenu_PeopleMenage;
	// End of variables declaration//GEN-END:variables

}