/*
 * PeopleMangeFrame.java
 *
 * Created on 2013
 */

package MyFrame;

import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.JOptionPane;

import MyDao.Until;

/**
 *
 * @author  fengche
 */
public class PeopleSerchFrame extends javax.swing.JInternalFrame {

	private String name = null;

	/** Creates new form PeopleMangeFrame */
	public PeopleSerchFrame() {
		initComponents();
		this.setLocation(300, 100);//窗口位置设定
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField_name = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField_age = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField_class = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField_number = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea_like = new javax.swing.JTextArea();
		jButton_edit = new javax.swing.JButton();
		jButton_select = new javax.swing.JButton();
		jButton_del = new javax.swing.JButton();
		jButton_ok = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jTextField_club = new javax.swing.JTextField();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u67e5\u8be2");

		jLabel1.setText("\u59d3\u540d\uff1a");

		jLabel2.setText("\u5e74\u9f84\uff1a");

		jTextField_age.setEditable(false);

		jLabel3.setText("\u73ed\u7ea7\uff1a");

		jTextField_class.setEditable(false);

		jLabel4.setText("\u5b66\u53f7\uff1a");

		jTextField_number.setEditable(false);

		jLabel5.setText("\u7231\u597d\uff1a");

		jTextArea_like.setColumns(20);
		jTextArea_like.setEditable(false);
		jTextArea_like.setRows(5);
		jScrollPane1.setViewportView(jTextArea_like);

		jButton_edit.setText("\u7f16\u8f91");
		jButton_edit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_editActionPerformed(evt);
			}
		});

		jButton_select.setText("\u67e5\u8be2");
		jButton_select.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_selectActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

		jButton_del.setText("\u5220\u9664");
		jButton_del.setEnabled(false);
		jButton_del.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_delActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

		jButton_ok.setText("\u786e\u5b9a");
		jButton_ok.setEnabled(false);
		jButton_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_okActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

		jLabel6.setText("\u534f\u4f1a\uff1a");

		jTextField_club.setEditable(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap(41, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel5)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								572,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												layout
																														.createSequentialGroup()
																														.addComponent(
																																jLabel4)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jTextField_number,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																105,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																														.addComponent(
																																jLabel2)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jTextField_age,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																56,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												layout
																														.createSequentialGroup()
																														.addComponent(
																																jLabel1)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jTextField_name,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																123,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																jButton_select)))
																						.addGap(
																								10,
																								10,
																								10)
																						.addComponent(
																								jLabel3)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jTextField_class,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								108,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel6)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jTextField_club)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton_del)
																		.addGap(
																				41,
																				41,
																				41)
																		.addComponent(
																				jButton_edit)
																		.addGap(
																				37,
																				37,
																				37)
																		.addComponent(
																				jButton_ok)))
										.addGap(75, 75, 75)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(32, 32, 32)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField_name,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton_select))
										.addGap(29, 29, 29)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField_number,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField_age,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																jTextField_class,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField_club,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(30, 30, 30)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel5)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																192,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												55, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton_del)
														.addComponent(
																jButton_ok)
														.addComponent(
																jButton_edit))
										.addGap(32, 32, 32)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	/**
	 *删除事件
	 */
	private void jButton_delActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		Until until = new Until();//声明一个until对象
		until.deletepeople(this.jTextField_number.getText());
		resetAll();//重置
		
	}
	/**
	 *确定事件
	 */
	private void jButton_okActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		peopleEdit();
	}
	/**
	 *查询事件
	 */
	private void jButton_selectActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		this.name = this.jTextField_name.getText();
		Until until = new Until();//声明一个until对象
		ArrayList<String> arrayList = new ArrayList<String>();
		if (!this.jTextField_name.getText().equals("")) {
			arrayList = until.selectpeople(jTextField_name.getText());
			Iterator<String> iterator = arrayList.iterator();
			this.jTextField_club.setText(iterator.next());
			this.jTextField_name.setText(iterator.next());
			this.jTextField_number.setText(iterator.next());
			this.jTextField_age.setText(iterator.next());
			this.jTextField_class.setText(iterator.next());
			this.jTextArea_like.setText(iterator.next());
		} else {
			JOptionPane.showMessageDialog(null, "名称不能为空!");//信息提示框
		}
	}
	/**
	 *people编辑
	 */
	private void peopleEdit() throws Exception {
		Until until = new Until();
		String Sname = this.jTextField_name.getText();
		String Sno = this.jTextField_number.getText();
		String Sage = this.jTextField_age.getText();
		String Sclass = this.jTextField_class.getText();
		String Slike = this.jTextArea_like.getText();
		String Sxiehui = this.jTextField_club.getText();
		until.updatepeople(name, Sname, Sno, Sage, Sclass, Slike, Sxiehui);
	}
	/**
	 *编辑事件
	 */
	private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {
		this.jTextArea_like.setEditable(true);
		this.jTextField_age.setEditable(true);
		this.jTextField_class.setEditable(true);
		this.jTextField_number.setEditable(true);
		this.jButton_ok.setEnabled(true);
		this.jButton_del.setEnabled(true);
	}
	/**
	 *重置
	 */
	private void resetAll() {
		this.jTextArea_like.setText("");
		this.jTextField_age.setText("");
		this.jTextField_class.setText("");
		this.jTextField_name.setText("");
		this.jTextField_number.setText("");
	}
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton_del;
	private javax.swing.JButton jButton_edit;
	private javax.swing.JButton jButton_ok;
	private javax.swing.JButton jButton_select;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea_like;
	private javax.swing.JTextField jTextField_age;
	private javax.swing.JTextField jTextField_class;
	private javax.swing.JTextField jTextField_club;
	private javax.swing.JTextField jTextField_name;
	private javax.swing.JTextField jTextField_number;
	// End of variables declaration//GEN-END:variables

}