/*
 * PeopleMangeFrame.java
 *
 * Created on 2013
 */

package MyFrame;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import MyDao.Until;

/**
 *
 * @author  fengche
 */
public class PeopleAddFrame extends javax.swing.JInternalFrame {

	/** Creates new form PeopleMangeFrame */
	public PeopleAddFrame() {
		initComponents();
		this.setLocation(300, 100);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField_name = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField_age = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField_class = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField_number = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea_like = new javax.swing.JTextArea();
		jButton_reset = new javax.swing.JButton();
		jButton_ok = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jComboBox_club = new javax.swing.JComboBox();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u6dfb\u52a0");

		jLabel1.setText("\u59d3\u540d\uff1a");

		jLabel2.setText("\u5e74\u9f84\uff1a");

		jLabel3.setText("\u73ed\u7ea7\uff1a");

		jLabel4.setText("\u5b66\u53f7\uff1a");

		jLabel5.setText("\u7231\u597d\uff1a");

		jTextArea_like.setColumns(20);
		jTextArea_like.setRows(5);
		jScrollPane1.setViewportView(jTextArea_like);

		jButton_reset.setText("\u91cd\u7f6e");
		jButton_reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_resetActionPerformed(evt);
			}
		});

		jButton_ok.setText("\u786e\u5b9a");
		jButton_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton_okActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel6.setText("\u6240\u5c5e\u534f\u4f1a\uff1a");

		jComboBox_club.setModel(new javax.swing.DefaultComboBoxModel(
				ClubLoad()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(41, 41, 41)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				385,
																				385,
																				385)
																		.addComponent(
																				jButton_ok)
																		.addGap(
																				38,
																				38,
																				38)
																		.addComponent(
																				jButton_reset))
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel5)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								520,
																								Short.MAX_VALUE))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel1)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jTextField_name,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								123,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								45,
																								45,
																								45)
																						.addComponent(
																								jLabel2)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jTextField_age,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								56,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								49,
																								49,
																								49)
																						.addComponent(
																								jLabel3)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jTextField_class,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								158,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel4)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jTextField_number,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								195,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(
																								38,
																								38,
																								38)
																						.addComponent(
																								jLabel6)
																						.addGap(
																								18,
																								18,
																								18)
																						.addComponent(
																								jComboBox_club,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								116,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(48, 48, 48)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(32, 32, 32)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField_name,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField_age,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																jTextField_class,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(29, 29, 29)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField_number,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6)
														.addComponent(
																jComboBox_club,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(30, 30, 30)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel5)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																192,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												39, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton_reset)
														.addComponent(
																jButton_ok))
										.addGap(30, 30, 30)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	/**
	 *确认事件按钮
	 */
	private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		if (jTextField_name.equals("")) {
			JOptionPane.showMessageDialog(null, "添加失败,姓名不能为空！");//信息提示框
		}
		else {
			fillAll();
			resetAll();
		}
	}
	/**
	 *重置事件按钮
	 */
	private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {
		resetAll();
	}
	/**
	 *填充事件方法
	 */
	private void fillAll() throws Exception{
		Until until = new Until();//声明一个until对象
		String Sname = this.jTextField_name.getText();
		String Sno = this.jTextField_number.getText();
		String Sage = this.jTextField_age.getText();
		String Sclass = this.jTextField_class.getText();
		String Slike = this.jTextArea_like.getText();
		String Sxiehui = this.jComboBox_club.getSelectedItem().toString();
		if (!this.jTextField_name.getText().equals("")) {
			until.insertStudent(Sname, Sno, Sage, Sclass, Slike, Sxiehui);
		}
	}
	/**
	 *重置事件方法
	 */
	private void resetAll() {
		this.jTextArea_like.setText("");
		this.jTextField_age.setText("");
		this.jTextField_class.setText("");
		this.jTextField_name.setText("");
		this.jTextField_number.setText("");
	}
	/**
	 *clubname获取方法
	 */
	private String[] ClubLoad(){
		ArrayList<String> arrayList = new ArrayList<String>();
		String[] sc = null;
		try {
			Until until = new Until();
			arrayList = until.selectClubName("ST_name", "Club");
			String[] strings = new String[arrayList.size()];
			strings = arrayList.toArray(strings);
			sc = strings;
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "数据库查询错误");
		}
		return sc;
	}
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton_ok;
	private javax.swing.JButton jButton_reset;
	private javax.swing.JComboBox jComboBox_club;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea_like;
	private javax.swing.JTextField jTextField_age;
	private javax.swing.JTextField jTextField_class;
	private javax.swing.JTextField jTextField_name;
	private javax.swing.JTextField jTextField_number;
	// End of variables declaration//GEN-END:variables

}